# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23794330401a0f870cba7e0580ff67350dcae23b8969e3e7eca4d59f9132a780490b6dd0904ce731080873527488dd80cc637447d68013969f49f6b5fbe4d1db

test:
  secret_key_base: c31d7b6d1c47082547b5a09c032a3bd77fbc0cd96128abbb2e1c4a0f0c67cdde6695706f21b696824424989b237404037c451b17e94ab90b64df41ea9bce69e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
